var a = 3;
var b = 5;
var d = a - b;
var e = a * b;
var f = a / b;
var g = a % b;
document.write(" Substraction of 3 and 5 is " + d + "<br>");
document.write(" Multiplication of 3 and 5 is " + e + "<br>");
document.write(" Division of 3 and 5 is " + f + "<br>");
document.write(" Modulus of 3 and 5 is " + g + "<br>");