var a;
document.write(" Declared: " + a + "<br>");
a = 5;
document.write(" Initial value: " + a + "<br>");
document.write(" Value after increment: " + ++a + "<br>");
a += 7;
document.write(" Value after adding 7: " + a + "<br>");
document.write(" Value after decrement: " + --a + "<br>");
a %= 3;
document.write(" Remainder value " + a + "<br>");